services :
  mongo_db:
    container_name : database_container
    image : mongo:latest
    restart : always 
    volumes : 
      - mongo_db:/data/db

  app : 
    build: . 
    container_name : app_container
    ports:
      - 3000:3000
    environment:
      port : 3000
      url : 'mongodb://mongo_db:27017/school'
      LOG_LEVEL : "info"
    volumes:
      - app-logs:/usr/src/app/
    depends_on:
      - mongo_db

volumes:
  mongo_db : 
  app-logs :
  
