services :
  mongo_db:
    container_name : database_container
    image : mongo:latest
    restart : always 
    volumes : 
      - mongo_db:/data/db


  app : 
    build: . 
    container_name : app_container
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - app-logs:/usr/src/app/logs
    depends_on:
      - mongo_db

volumes:
  mongo_db : 
  app-logs :
  
